FamilyFun.Web/Controllers/MitzvosController.cs
using FamilyFun.Persistence.Models;
using FamilyFun.Web.Models;
using FamilyFun.Web.Models.ViewModels;
using FamilyFun.Web.Persistance;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FamilyFun.Web.Controllers
{
    [Route("[controller]")]
    public class MitzvosController : Controller
    {
        private readonly IMitzvahRepository _mitzvahRepository;
        private readonly IPageColorDeterminer _colorDeterminer;
        private readonly IMitzvosSelectorElementRetriever _mitzvosSelectorRetriever;
        private readonly IFamilyMembersRetriever _familyMembersRetriever;
        private readonly IMitzvosRetriever _mitzvosRetriever;

        public MitzvosController(IPageColorDeterminer colorDeterminer, IMitzvosSelectorElementRetriever mitzvosSelectorRetriever, 
            IMitzvahRepository mitzvahLogger, IFamilyMembersRetriever familyMembersRetriever, IMitzvosRetriever mitzvosRetriever)
        {
            _colorDeterminer = colorDeterminer ?? throw new ArgumentNullException(nameof(colorDeterminer));
            _mitzvosSelectorRetriever = mitzvosSelectorRetriever ?? throw new ArgumentNullException(nameof(mitzvosSelectorRetriever));
            _mitzvahRepository = mitzvahLogger ?? throw new ArgumentNullException(nameof(mitzvahLogger));
            _familyMembersRetriever = familyMembersRetriever ?? throw new ArgumentNullException(nameof(familyMembersRetriever));
            _mitzvosRetriever = mitzvosRetriever ?? throw new ArgumentNullException(nameof(mitzvosRetriever));
        }

        [HttpGet("{id}")]
        public IActionResult Index(int id)
        {
            ViewBag.PageColors = _colorDeterminer.DeterminePageBackgroundColors();
            IEnumerable<SelectorElement> mitzvosSelectors = _mitzvosSelectorRetriever.RetrieveByFamilyMemberId(id).ToList();

            return View("MitzvahMenuSelector", new MitzvahMenuModelView(id, mitzvosSelectors));
        }

        [HttpPost("")]
        public async Task<IActionResult> AddMitzvah(MitzvahOccuranceViewModel mitzvahOccurance)
        {
            mitzvahOccurance.MitzvahDate = mitzvahOccurance.MitzvahDate ?? DateTime.Today;

            if (await _mitzvahRepository.MemberHasMitzvahForDate(mitzvahOccurance.FamilyMemberId, mitzvahOccurance.MitzvahId, mitzvahOccurance.MitzvahDate.Value))
            {
                ModelState.AddModelError("mitzvahId", "Mitzvah already exists");
            }

            if (ModelState.IsValid)
            {
                FamilyMember member = _familyMembersRetriever.RetrieveFamilyMembers(m => m.Id == mitzvahOccurance.FamilyMemberId).Single();
                Mitzvah mitzvah = _mitzvosRetriever.RetrieveMitzvos(m => m.Id == mitzvahOccurance.MitzvahId).Single();

                ViewBag.PageColors = _colorDeterminer.DeterminePageBackgroundColors();
                await _mitzvahRepository.LogMitzvahPointsForDateAsync(mitzvahOccurance.FamilyMemberId, mitzvahOccurance.MitzvahId, mitzvahOccurance.MitzvahDate.Value, mitzvah.Points);

                return View(new AddMitzvahResult(member.Id, member.Name, mitzvah.Points));
            }

            return Index(mitzvahOccurance.FamilyMemberId);
        }

        [HttpGet("Admin/{fmId}/{date}")]
        public async Task<IActionResult> ViewLoggedMitzvos([FromRoute] int fmId, [FromRoute] DateTime date)
        {
            IDictionary<int, Mitzvah> mitzvos = _mitzvosRetriever.RetrieveMitzvos().ToDictionary(k => k.Id, v => v);
            IDictionary<int, FamilyMember> familyMembers = _familyMembersRetriever.RetrieveFamilyMembers().ToDictionary(k => k.Id, v => v);

            IEnumerable<MitzvahOccurence>? mitvosOccurances = await _mitzvahRepository.RetrieveAllMitzvahOccurencesAsync(fmId, date);
            IEnumerable<LoggedMitzvahViewModel> mitzvahOccurancesViewModels = mitvosOccurances
                .Select(mo => new LoggedMitzvahViewModel(mo.Id, familyMembers[mo.FamilyMemberId], mitzvos[mo.MitzvahId], mo.Points, mo.OccuredOn, mo.ApproveOn, mo.ApprovedBy));

            return View("LoggedMitzvos", mitzvahOccurancesViewModels);
        }

        [HttpGet("Approve/{id}")]
        public async Task<JsonResult> ApproveMitzvah(string id)
        {
            MitzvahOccurence mitzvahOccurence = await _mitzvahRepository.RetrieveSinlgeMitzvahOccuranceAsync(id);
            mitzvahOccurence.ApproveOn = DateTime.Now;
            mitzvahOccurence.ApprovedBy = "Anonymous";
            await _mitzvahRepository.UpdateAsync(mitzvahOccurence);

            return Json(new { success = true });
        }

        [HttpGet("Block/{id}")]
        public async Task<JsonResult> BlockMitzvah(string id)
        {
            MitzvahOccurence mitzvahOccurence = await _mitzvahRepository.RetrieveSinlgeMitzvahOccuranceAsync(id);
            mitzvahOccurence.ApproveOn = DateTime.Now;
            mitzvahOccurence.ApprovedBy = "Anonymous";
            mitzvahOccurence.Points = 0;
            await _mitzvahRepository.UpdateAsync(mitzvahOccurence);

            return Json(new { success = true });
        }

        [HttpGet("Delete/{id}")]
        public async Task<JsonResult> DeleteMitzvah(string id)
        {
            await _mitzvahRepository.DeleteSinlgeMitzvahOccuranceAsync(id);

            return Json(new { success = true });
        }
    }
}

FamilyFun.Web/Views/Mitzvos/LoggedMitzvos.cshtml
@model IEnumerable<FamilyFun.Web.Models.ViewModels.LoggedMitzvahViewModel>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Family Member")
            </th>
            <th>
                @Html.DisplayName("Mitzvah")
            </th>
            <th>
                @Html.DisplayName("Occured On")
            </th>
            <th>
                @Html.DisplayName("Points")
            </th>
            <th>
                @Html.DisplayName("Approved On")
            </th>
            <th>
                @Html.DisplayName("Approved By")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="loggedMitzvos">
        @if (Model.Any())
        {
            @Html.DisplayFor(model => Model)
        }
        else
        {
            <tr><td colspan="3">No Records to display.</td></tr>
        }
    </tbody>
</table>

FamilyFun.Web/Views/Mitzvos/MitzvahMenuSelector.cshtml
@model MitzvahMenuModelView
@using FamilyFun.Web.Models.ViewModels

@{
    Layout = "_ColorfulBodyLayout";
    await Html.RenderPartialAsync("_MenuSelectorPartial", Model.MitzvahSelectors);

    await Html.RenderPartialAsync("_AdminModalOpener", new AdminModalViewModel("_MitzvahSelectorAdminModal", new MitzvahAdminViewModel(Model.FamilyMemberId)));
}

@section Scripts
{
    <script src="~/js/date_selector.js"></script>
    <script>
        var currentDate = '@DateTime.Today.ToString("yyyy-MM-dd")';
        $('#admin-modal').on('shown.bs.modal', function () {
            $('#mitzvahOccurances')
                .load('@Url.Action("ViewLoggedMitzvos", "Mitzvos", new { fmId = Model.FamilyMemberId, date = DateTime.Today.ToString("yyyy-MM-dd") })', linkActions);
        });
        $('#mitzvahDateSelector').addDataSelector({
            onChange: function (selectedDate) {
                currentDate = selectedDate;
                $('[name=MitzvahDate]').val(selectedDate);
                $('#mitzvahOccurances').load('Admin/@Model.FamilyMemberId/' + selectedDate, linkActions);
            },
            defaultDate: currentDate
        });
        var linkActions = function () {
            $("#loggedMitzvos .actions a").click(function (event) {
                event.preventDefault();

                $.get($(this).attr("href"))
                    .done(function () {
                        $('#mitzvahOccurances').load('Admin/@Model.FamilyMemberId/' + currentDate, linkActions);
                    })
            });
        };
    </script>
}

FamilyFun.Web/Views/Mitzvos/_MitzvahSelectorAdminModal.cshtml
@model FamilyFun.Web.Models.ViewModels.MitzvahAdminViewModel
<
<div id="mitzvahDateSelector">

</div>
<div id="mitzvahOccurances">

</div>